import System.IO
import Data.Char

-- This code was generated by ChatGPT, I wanted to test it out
--
main = do
  file <- readFile "input.txt"
  let lins = map (map (\c ->
        if c >= 'A' && c <= 'C'
          then ord c - ord 'A'
          else ord c - ord 'X')
        . map head
        . words) (lines file)
  print $ sum $ map (\line -> (line !! 1 - line !! 0 + 4) `mod` 3 * 3 + line !! 1 + 1) lins
  print $ sum $ map (\line -> (line !! 0 + line !! 1 + 2) `mod` 3 + line !! 1 * 3 + 1) lins
