import System.IO
import Data.List.Split

-- This code was generated by ChatGPT, I wanted to test it out

main = do
  file <- readFile "input.txt"
  let lines = splitOn "\n" file
  let games = map (splitOn " ") lines
  print $ calculateScore games
  let preparedGames = prepare games
  print $ calculateScore preparedGames

prepare games = map (\game ->
  if length game /= 2
    then game
    else case (head game, game !! 1) of
      ("A", "X") -> ["A", "Z"]
      ("A", "Y") -> ["A", "X"]
      ("A", "Z") -> ["A", "Y"]
      ("B", "X") -> ["B", "X"]
      ("B", "Y") -> ["B", "Y"]
      ("B", "Z") -> ["B", "Z"]
      ("C", "X") -> ["C", "Y"]
      ("C", "Y") -> ["C", "Z"]
      ("C", "Z") -> ["C", "X"]) games

calculateScore games = sum $ map (\game ->
  if length game /= 2
    then 0
    else case game !! 1 of
      "X" -> case head game of
        "A" -> 4
        "B" -> 1
        "C" -> 7
      "Y" -> case head game of
        "A" -> 8
        "B" -> 5
        "C" -> 2
      "Z" -> case head game of
        "A" -> 4
        "B" -> 9
        "C" -> 6) games

